### ISSUE TITLE
Possible Problem With Logical Negation Operator

### ISSUE THREAD

**Issue by dharapa** [vianuevm/cppStyle#127] opened 2015-01-28 03:26 UTC
Receiving an error: "Incorrect spacing around !.  If this is a negative variable, you must write it as -(myVariable) using parentheses." when using the logical negation operator. 

However, it appears to be implemented correctly and the program produces the right output.

**Comment by willwolf** [comment] 2015-03-03 05:26
Should be resolved in beac130a7bdc2ea318e1116226f395649055c5f5.  Please resubmit the code the exposed this issue and verify the issue is resolved.  If you find that it is not resolved, please reopen the issue and let me know :)

**Closed by willwolf** 2015-03-03 05:26 UTC

**Comment by dharapa** [comment] 2015-03-04 21:55
Issue has been resolved! (:
